import { TeamApplication, Player } from '../types';

// Add after mockTeams

// Mock Team Applications
export const mockTeamApplications: TeamApplication[] = [
  {
    id: 'app-1',
    teamId: 'team-3',
    leagueId: 'league-1',
    status: 'pending',
    appliedDate: '2024-11-20T10:00:00Z',
    notes: 'We are excited to join the Manhattan Basketball League!',
  },
  {
    id: 'app-2',
    teamId: 'team-4',
    leagueId: 'league-1',
    status: 'pending',
    appliedDate: '2024-11-21T14:30:00Z',
    notes: 'Experienced team looking for competitive play.',
  },
  {
    id: 'app-3',
    teamId: 'team-5',
    leagueId: 'league-2',
    status: 'approved',
    appliedDate: '2024-11-15T09:00:00Z',
    reviewedDate: '2024-11-16T11:00:00Z',
    reviewedBy: 'admin-1',
  },
  {
    id: 'app-4',
    teamId: 'team-6',
    leagueId: 'league-1',
    status: 'rejected',
    appliedDate: '2024-11-18T16:00:00Z',
    reviewedDate: '2024-11-19T10:00:00Z',
    reviewedBy: 'admin-1',
    rejectionReason: 'Team does not meet minimum player count requirement (need at least 5 players).',
  },
];

// Mock Players
export const mockPlayers: Player[] = [
  {
    id: 'player-1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    phone: '+1-555-0101',
    avatar: 'https://i.pravatar.cc/150?u=player1',
    dateOfBirth: '1995-05-15',
    sports: ['basketball', 'soccer'],
    skillLevel: 'advanced',
    position: 'Point Guard',
    teams: ['team-1'],
    gamesPlayed: 45,
    stats: {
      wins: 32,
      losses: 13,
      winRate: 0.71,
    },
  },
  {
    id: 'player-2',
    name: 'Jane Smith',
    email: 'jane.smith@example.com',
    phone: '+1-555-0102',
    avatar: 'https://i.pravatar.cc/150?u=player2',
    dateOfBirth: '1992-08-22',
    sports: ['basketball'],
    skillLevel: 'advanced',
    position: 'Shooting Guard',
    teams: ['team-1'],
    gamesPlayed: 38,
    stats: {
      wins: 28,
      losses: 10,
      winRate: 0.74,
    },
  },
  {
    id: 'player-3',
    name: 'Mike Johnson',
    email: 'mike.j@example.com',
    phone: '+1-555-0103',
    avatar: 'https://i.pravatar.cc/150?u=player3',
    dateOfBirth: '1998-03-10',
    sports: ['basketball', 'tennis'],
    skillLevel: 'intermediate',
    position: 'Center',
    teams: ['team-1'],
    gamesPlayed: 23,
    stats: {
      wins: 15,
      losses: 8,
      winRate: 0.65,
    },
  },
  {
    id: 'player-4',
    name: 'Sarah Williams',
    email: 'sarah.w@example.com',
    phone: '+1-555-0104',
    avatar: 'https://i.pravatar.cc/150?u=player4',
    dateOfBirth: '1994-11-05',
    sports: ['basketball', 'volleyball'],
    skillLevel: 'professional',
    position: 'Power Forward',
    teams: ['team-2'],
    gamesPlayed: 67,
    stats: {
      wins: 52,
      losses: 15,
      winRate: 0.78,
    },
  },
  {
    id: 'player-5',
    name: 'Tom Brown',
    email: 'tom.brown@example.com',
    phone: '+1-555-0105',
    avatar: 'https://i.pravatar.cc/150?u=player5',
    dateOfBirth: '1996-07-18',
    sports: ['basketball'],
    skillLevel: 'intermediate',
    position: 'Small Forward',
    teams: ['team-2'],
    gamesPlayed: 31,
    stats: {
      wins: 20,
      losses: 11,
      winRate: 0.65,
    },
  },
  {
    id: 'player-6',
    name: 'Alex Rodriguez',
    email: 'alex.r@example.com',
    phone: '+1-555-0106',
    avatar: 'https://i.pravatar.cc/150?u=player6',
    dateOfBirth: '1997-01-25',
    sports: ['basketball', 'soccer'],
    skillLevel: 'advanced',
    position: 'Point Guard',
    teams: ['team-3'],
    gamesPlayed: 12,
    stats: {
      wins: 7,
      losses: 5,
      winRate: 0.58,
    },
  },
  {
    id: 'player-7',
    name: 'Emily Davis',
    email: 'emily.d@example.com',
    phone: '+1-555-0107',
    avatar: 'https://i.pravatar.cc/150?u=player7',
    dateOfBirth: '1999-09-14',
    sports: ['soccer', 'tennis'],
    skillLevel: 'beginner',
    position: 'Midfielder',
    teams: [],
    gamesPlayed: 5,
    stats: {
      wins: 2,
      losses: 3,
      winRate: 0.40,
    },
  },
  {
    id: 'player-8',
    name: 'Chris Martinez',
    email: 'chris.m@example.com',
    phone: '+1-555-0108',
    avatar: 'https://i.pravatar.cc/150?u=player8',
    dateOfBirth: '1993-12-30',
    sports: ['basketball'],
    skillLevel: 'professional',
    position: 'Center',
    teams: [],
    gamesPlayed: 89,
    stats: {
      wins: 72,
      losses: 17,
      winRate: 0.81,
    },
  },
];
