import { Facility, FacilityBooking } from '../types';

// Mock Facilities
export const mockFacilities: Facility[] = [
  {
    id: 'facility-1',
    name: 'Manhattan Sports Complex',
    ownerId: 'facility-admin-1',
    ownerName: 'Sports Facilities Inc.',
    address: '123 Sports Ave',
    city: 'New York',
    state: 'NY',
    zipCode: '10001',
    description: 'Premier indoor sports facility with state-of-the-art equipment and multiple courts. Perfect for basketball, volleyball, and indoor soccer.',
    sports: ['basketball', 'volleyball', 'indoor soccer', 'badminton'],
    amenities: ['Parking', 'WiFi', 'Locker Rooms', 'Showers', 'Concessions', 'AC/Heating', 'Scoreboard'],
    capacity: 500,
    squareFootage: 25000,
    indoorOutdoor: 'indoor',
    hourlyRate: 200,
    dailyRate: 1500,
    weeklyRate: 9000,
    monthlyRate: 30000,
    equipment: [
      {
        id: 'equip-1',
        name: 'Basketball Hoops (Adjustable)',
        category: 'sports',
        quantity: 6,
        pricePerHour: 0, // Included
        pricePerDay: 0,
        condition: 'excellent',
        description: 'Professional adjustable basketball hoops',
      },
      {
        id: 'equip-2',
        name: 'Volleyball Net System',
        category: 'sports',
        quantity: 2,
        pricePerHour: 25,
        pricePerDay: 100,
        condition: 'excellent',
      },
      {
        id: 'equip-3',
        name: 'Sound System & Microphone',
        category: 'audio-visual',
        quantity: 1,
        pricePerHour: 50,
        pricePerDay: 200,
        condition: 'good',
      },
      {
        id: 'equip-4',
        name: 'Folding Chairs',
        category: 'seating',
        quantity: 200,
        pricePerHour: 50,
        pricePerDay: 150,
        condition: 'good',
      },
      {
        id: 'equip-5',
        name: 'First Aid Station',
        category: 'safety',
        quantity: 2,
        pricePerHour: 0, // Included
        pricePerDay: 0,
        condition: 'excellent',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800',
      'https://images.unsplash.com/photo-1519505907962-0a6cb0167c73?w=800',
    ],
    availability: {
      monday: { open: '06:00', close: '22:00', available: true },
      tuesday: { open: '06:00', close: '22:00', available: true },
      wednesday: { open: '06:00', close: '22:00', available: true },
      thursday: { open: '06:00', close: '22:00', available: true },
      friday: { open: '06:00', close: '23:00', available: true },
      saturday: { open: '08:00', close: '23:00', available: true },
      sunday: { open: '08:00', close: '20:00', available: true },
    },
    rating: 4.8,
    totalBookings: 245,
    status: 'active',
    contactPhone: '+1-555-0301',
    contactEmail: 'booking@manhattansports.com',
    createdAt: '2023-01-15T00:00:00Z',
  },
  {
    id: 'facility-2',
    name: 'Brooklyn Fieldhouse',
    ownerId: 'facility-admin-2',
    ownerName: 'Brooklyn Recreation LLC',
    address: '456 Field St',
    city: 'Brooklyn',
    state: 'NY',
    zipCode: '11201',
    description: 'Large outdoor field complex ideal for soccer, football, and lacrosse. Features synthetic turf and stadium lighting.',
    sports: ['soccer', 'football', 'lacrosse', 'ultimate frisbee'],
    amenities: ['Parking', 'Restrooms', 'Stadium Lighting', 'Bleacher Seating', 'Water Fountains'],
    capacity: 1000,
    squareFootage: 80000,
    indoorOutdoor: 'outdoor',
    hourlyRate: 150,
    dailyRate: 1200,
    weeklyRate: 7500,
    equipment: [
      {
        id: 'equip-6',
        name: 'Soccer Goals (Full Size)',
        category: 'sports',
        quantity: 4,
        pricePerHour: 0, // Included
        pricePerDay: 0,
        condition: 'excellent',
      },
      {
        id: 'equip-7',
        name: 'Portable Bleachers',
        category: 'seating',
        quantity: 4,
        pricePerHour: 75,
        pricePerDay: 300,
        condition: 'good',
        description: 'Each seats 50 people',
      },
      {
        id: 'equip-8',
        name: 'Training Cones (Set of 50)',
        category: 'sports',
        quantity: 3,
        pricePerHour: 10,
        pricePerDay: 25,
        condition: 'good',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1589487391730-58f20eb2c308?w=800',
    ],
    availability: {
      monday: { open: '07:00', close: '21:00', available: true },
      tuesday: { open: '07:00', close: '21:00', available: true },
      wednesday: { open: '07:00', close: '21:00', available: true },
      thursday: { open: '07:00', close: '21:00', available: true },
      friday: { open: '07:00', close: '22:00', available: true },
      saturday: { open: '07:00', close: '22:00', available: true },
      sunday: { open: '08:00', close: '20:00', available: true },
    },
    rating: 4.6,
    totalBookings: 189,
    status: 'active',
    contactPhone: '+1-555-0302',
    contactEmail: 'info@brooklynfield.com',
    createdAt: '2023-03-20T00:00:00Z',
  },
  {
    id: 'facility-3',
    name: 'Queens Multi-Purpose Arena',
    ownerId: 'facility-admin-1',
    ownerName: 'Sports Facilities Inc.',
    address: '789 Arena Blvd',
    city: 'Queens',
    state: 'NY',
    zipCode: '11354',
    description: 'Versatile indoor/outdoor facility with retractable roof. Suitable for all weather conditions and various sports.',
    sports: ['basketball', 'volleyball', 'tennis', 'badminton', 'futsal'],
    amenities: ['Parking', 'WiFi', 'Locker Rooms', 'Showers', 'Cafe', 'Pro Shop', 'Retractable Roof'],
    capacity: 750,
    squareFootage: 35000,
    indoorOutdoor: 'both',
    hourlyRate: 250,
    dailyRate: 2000,
    weeklyRate: 12000,
    monthlyRate: 40000,
    equipment: [
      {
        id: 'equip-9',
        name: 'Professional Sound System',
        category: 'audio-visual',
        quantity: 1,
        pricePerHour: 75,
        pricePerDay: 300,
        condition: 'excellent',
      },
      {
        id: 'equip-10',
        name: 'Video Recording System',
        category: 'audio-visual',
        quantity: 1,
        pricePerHour: 100,
        pricePerDay: 400,
        condition: 'excellent',
        description: 'Multi-camera setup with instant replay',
      },
      {
        id: 'equip-11',
        name: 'Tournament Tables & Chairs',
        category: 'seating',
        quantity: 50,
        pricePerHour: 100,
        pricePerDay: 300,
        condition: 'good',
      },
    ],
    images: [
      'https://images.unsplash.com/photo-1577223625816-7546f13df25d?w=800',
    ],
    availability: {
      monday: { open: '05:00', close: '23:00', available: true },
      tuesday: { open: '05:00', close: '23:00', available: true },
      wednesday: { open: '05:00', close: '23:00', available: true },
      thursday: { open: '05:00', close: '23:00', available: true },
      friday: { open: '05:00', close: '00:00', available: true },
      saturday: { open: '06:00', close: '00:00', available: true },
      sunday: { open: '06:00', close: '22:00', available: true },
    },
    rating: 4.9,
    totalBookings: 312,
    status: 'active',
    contactPhone: '+1-555-0303',
    contactEmail: 'booking@queensarena.com',
    createdAt: '2022-11-10T00:00:00Z',
  },
];

// Mock Facility Bookings
export const mockFacilityBookings: FacilityBooking[] = [
  {
    id: 'booking-1',
    facilityId: 'facility-1',
    facilityName: 'Manhattan Sports Complex',
    bookingType: 'camp',
    relatedId: 'camp-1',
    bookedBy: 'trainer-1',
    bookedByName: 'Mike Johnson',
    startDateTime: '2025-06-15T09:00:00Z',
    endDateTime: '2025-06-15T17:00:00Z',
    duration: 8,
    equipmentRented: [
      { equipmentId: 'equip-3', name: 'Sound System & Microphone', quantity: 1, cost: 400 },
      { equipmentId: 'equip-4', name: 'Folding Chairs', quantity: 30, cost: 150 },
    ],
    totalCost: 2150, // 8 hours * 200 + equipment
    status: 'confirmed',
    notes: 'Youth Basketball Camp - Need setup by 8:30 AM',
    createdAt: '2025-05-01T10:00:00Z',
  },
  {
    id: 'booking-2',
    facilityId: 'facility-1',
    facilityName: 'Manhattan Sports Complex',
    bookingType: 'game',
    relatedId: 'game-1',
    bookedBy: 'admin',
    bookedByName: 'League Administrator',
    startDateTime: '2025-12-01T19:00:00Z',
    endDateTime: '2025-12-01T22:00:00Z',
    duration: 3,
    equipmentRented: [
      { equipmentId: 'equip-3', name: 'Sound System & Microphone', quantity: 1, cost: 150 },
    ],
    totalCost: 750, // 3 hours * 200 + equipment
    status: 'confirmed',
    notes: 'Championship game - need extra seating',
    createdAt: '2025-11-01T14:00:00Z',
  },
  {
    id: 'booking-3',
    facilityId: 'facility-2',
    facilityName: 'Brooklyn Fieldhouse',
    bookingType: 'training',
    bookedBy: 'trainer-2',
    bookedByName: 'Sarah Williams',
    startDateTime: '2025-12-10T14:00:00Z',
    endDateTime: '2025-12-10T18:00:00Z',
    duration: 4,
    equipmentRented: [
      { equipmentId: 'equip-8', name: 'Training Cones (Set of 50)', quantity: 2, cost: 100 },
    ],
    totalCost: 700, // 4 hours * 150 + equipment
    status: 'pending',
    notes: 'Team practice session',
    createdAt: '2025-12-01T09:00:00Z',
  },
];

export default {
  mockFacilities,
  mockFacilityBookings,
};
